spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stocks-portfolio
    username: postgres
    password: postgres
  jpa.hibernate.ddl-auto: update

amazon:
  accessKey: ${AMAZON_ACCESS_KEY}
  secretKey: ${AMAZON_SECRET_KEY}

gateway:
  url:
    stocks: http://localhost:8089/stocks

server:
  tomcat:
    max-threads: 200