spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stocks-portfolio
    username: postgres
    password: postgres
  jpa.hibernate.ddl-auto: validate

amazon:
  accessKey: ${AMAZON_ACCESS_KEY}
  secretKey: ${AMAZON_SECRET_KEY}

gateway:
  url:
    stocks: https://ar-stocks.herokuapp.com/

server:
  tomcat:
    max-threads: 200

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus